version: "3.9"
services:
  frontend:
    container_name: chat_app_frontend
    image: node:current-alpine3.16
    volumes:
      - "../frontend:/usr/src/chat_app_frontend"
    working_dir: "/usr/src/chat_app_frontend"
    command: node
    ports:
      - "3000:3000"
  backend:
    container_name: chat_app_backend
    image: node:current-alpine3.16
    volumes:
      - "../backend:/usr/src/chat_app_backend"
    working_dir: "/usr/src/chat_app_backend"
    command: npm run start
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=chat_app_database
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=database
      - DB_PORT=5432
      - DB_DIALECT=postgres
    depends_on:
      - database
  database:
    container_name: chat_app_database
    image: postgres:15.0-alpine
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_DB=chat_app_db
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin